"""Postgres access via DATABASE_URL.

Intended Supabase project: nfgoyspfbcpnlrpmxpgv (API base
https://nfgoyspfbcpnlrpmxpgv.supabase.co). Configure the Postgres connection
string from that project’s Settings → Database (not TrueDB / other projects).
"""

import logging
import os
from contextlib import contextmanager
from typing import Any, Generator

import psycopg
from fastapi import HTTPException
from psycopg.rows import dict_row

from .models import JobInfo

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)


def _dsn() -> str:
    d = (os.environ.get("DATABASE_URL") or "").strip()
    if not d:
        raise HTTPException(
            status_code=503,
            detail="Database is not configured (set DATABASE_URL to your Supabase Postgres URI).",
        )
    return d


@contextmanager
def _conn() -> Generator[psycopg.Connection[Any], None, None]:
    with psycopg.connect(_dsn(), autocommit=False) as conn:
        yield conn


def create_tables() -> None:
    try:
        with _conn() as dbconn:
            with dbconn.cursor() as cur:
                cur.execute(
                    """CREATE TABLE IF NOT EXISTS job_applications (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at    TEXT NOT NULL,
                job_url       TEXT,
                job_text      TEXT NOT NULL,
                resume_choice TEXT,
                job_title     TEXT,
                salary        TEXT,
                job_summary   TEXT
                );"""
                )
            dbconn.commit()
    except psycopg.Error as e:
        logger.exception("create_tables failed")
        raise HTTPException(503, "Could not connect to database.") from e


def add_job(info_to_add: JobInfo) -> None:
    try:
        with _conn() as dbconn:
            with dbconn.cursor() as cur:
                cur.execute(
                    """
            INSERT into job_applications (
                created_at, job_url, job_text, resume_choice,
                job_title, salary, job_summary
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
                    (
                        info_to_add.created_at,
                        info_to_add.job_url,
                        info_to_add.job_text,
                        info_to_add.resume_choice,
                        info_to_add.job_title,
                        info_to_add.salary,
                        info_to_add.job_summary,
                    ),
                )
            dbconn.commit()
    except psycopg.Error:
        logger.exception("add_job failed", exc_info=True)
        raise HTTPException(503, "Could not save job")


def del_job(job_id: int) -> int:
    """Delete a row by id. Returns number of rows removed (0 if id did not exist)."""
    try:
        with _conn() as dbconn:
            with dbconn.cursor() as cur:
                cur.execute(
                    "DELETE FROM job_applications WHERE id = %s",
                    (job_id,),
                )
                n = int(cur.rowcount)
            dbconn.commit()
            return n
    except psycopg.Error as e:
        logger.exception("del_job failed", exc_info=True)
        raise HTTPException(503, "Could not delete job") from e


def get_jobs() -> list[dict[str, Any]]:
    try:
        with _conn() as dbconn:
            with dbconn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                SELECT id, created_at, job_url, job_text, resume_choice,
                       job_title, salary, job_summary
                FROM job_applications
                ORDER BY id DESC
                """
                )
                rows = cur.fetchall()
        return [dict(r) for r in rows]
    except psycopg.Error:
        logger.exception("get_jobs failed", exc_info=True)
        raise HTTPException(503, "Could not load jobs")
